### ISSUE TITLE
Update the boolean binding example for <vaadin-select>

### ISSUE THREAD

**Issue by platosha** [vaadin/docs#1474]
Now that the Hilla form binder supports binding boolean fields to `<vaadin-select>`, we should include it in the example here: https://hilla.dev/docs/data-binding/vaadin-components/#binding-data-to-boolean-fields

The source of the article: https://github.com/vaadin/docs/blob/hilla/articles/data-binding/vaadin-components.asciidoc

See the feature ticket for the usage code example: https://github.com/vaadin/hilla/issues/177

Use the `selectRenderer` included in `23.1` `<vaadin-select>`: https://github.com/vaadin/web-components/pull/3775

**Comment by cromoteca** [comment]
The given example doesn't work with the `select` renderer. It works if I bind to a `string`, but not if I bind to a `boolean` or to an `int`. The issue is not on the new `selectRenderer`. The renderer is not able to match the initial or changed value with the items inside itself, so the value is not selected.
