### ISSUE TITLE
Add environment variable VAADIN_PRO_KEY as a way to specify the license key to the documentation

### ISSUE THREAD

**Issue by simasch** [vaadin/docs#1698]
Adding the license key also works with an environment variable VAADIN_PRO_KEY

Please add this to:
https://vaadin.com/docs/latest/testing/browser-based/ci-server/#testbench.ci-server.license

**Comment by jouni** [comment]
Updated in https://github.com/vaadin/docs/commit/f344a4335f9ccfe55ae23c048152f357f001005f

**Comment by mcollovati** [comment]
I may be wrong, but offline key seems to have its own environment variable `VAADIN_OFFLINE_KEY`
Or are proKey and offlineKey interchangeable?

**Comment by jouni** [comment]
@Artur- please advice

**Comment by Artur-** [comment]
There are two different keys: proKey used for online validation and offlineKey used for offline validation.

A proKey can be defined using the `vaadin.proKey` system property or the `VAADIN_PRO_KEY` environment variable
An offlineKey can be defined using the `vaadin.offlineKey` system property or the `VAADIN_OFFLINE_KEY` environment variable.

**Comment by simasch** [comment]
@Artur- 
Now I'm confused. When to use which one?

**Comment by jouni** [comment]
Well, at least it looks like the instructions I added are misleading, as they say to use the offlineKey string as the value for VAADIN_PRO_KEY.

**Comment by Artur-** [comment]
An offline key is meant for offline development environments. It expires and needs to be renewed with a certain interval.

A pro key is meant for all other development cases. It keeps working without any manual work as long as you have a subscription and an internet connection.

**Comment by Artur-** [comment]
Maybe we should fix this in the checker so you can use `VAADIN_KEY` for any type of key

**Comment by simasch** [comment]
@Artur- now you've got me confused even more.

Why do I need an internet connection if I have a proKey locally on my machine?
IMO either the license should be checked online or local but both?

**Comment by jouni** [comment]
You need a connection for the first time, then the proKey is downloaded and stored locally. After that no connection is needed.

**Comment by jouni** [comment]
> Maybe we should fix this in the checker so you can use VAADIN_KEY for any type of key

Maybe. But I think users don't need to be concerned with proKey at all, as that should work transparently. If you need a key for offline or server/CI use, then you use offlineKey.

**Comment by simasch** [comment]
@jouni ok but then what's the purpose of the offline key?
I mean to get an offline key I need at least once an internet connection

**Comment by jouni** [comment]
@simasch sure, but you can use a different device to download the offline license key, and then transfer that to another computer that is never connected to the internet.

**Comment by jouni** [comment]
And perhaps I don't know exactly how/when proKey is checked, so maybe you do always need a connection when that is checked.

**Comment by simasch** [comment]
@jouni And the most confusing is this:

VAADIN_PRO_KEY=[contents of offlineKey file here]

**Comment by Avec112** [comment]
I want to present our problem so we are not forgotten here. 

We cannot and will never be able to connect my development computer online.  We are 100% offline always. I can however download a key from Internet and transfer it to my offline development computer. This is a cumbersome task and nothing I would like to do often. I prefer once a year when the key has expired just like it has been until now.

**Comment by jouni** [comment]
@Avec112, the new offline license should work fine for your use case. But you need the machine ID.

Note, that there was a bug in the server license key generator, which prevents it from working. This has been fixed in the license checker, but it will take some time to get released, so that any key that was downloaded already will start working. 

The generator was also fixed (on vaadin.com/myaccount/licenses), so any new keys should work without updating your Vaadin version (although I’m not 100% sure if that fix has been deployed yet).

**Comment by jouni** [comment]
Did another revision in https://github.com/vaadin/docs/commit/27020d7a7a5c03851cd168e41654eaa8d02f730f

**Comment by Avec112** [comment]
> Right now I cannot run anything because the license is no longer valid after upgrade to 23.2.0. I do not know what to do right now except for rolling back.

I had pointed `tools.vaadin.com` to `127.0.0.1` in my hosts file since I am offline. That stopped the Machine-id to become generated or at least show. After removing this from my hosts file the machine id was displayed in the build log. Everything is working as expected now. I have to renew the license in November however. Wish that was not necessary since this means more work.

**Comment by jouni** [comment]
Good to hear you got the builds running again. Apologies for the inconvenience and time lost on that.

Is your subscription expiring in November? I assume you would prefer if your license keys were automatically extended if/when your subscription renews, so that the keys would stay active for a full year before needing to regenerate them?

**Comment by Avec112** [comment]
Thanks. You are correct. It expires in November. That explains why I have to renew the key the same date. 
This is perfect. Just how I wanted it to be.

**Comment by jouni** [comment]
Alright, good. 

But to clarify: **at the moment license keys ares not auto-renewed**, and you will need to download a new one when your subscription renews.

**Comment by Avec112** [comment]
That is very understandable since I am offline.
