### ISSUE TITLE
`frontend.hotdeploy` configuration property not described on 'Configuration Properties' page

### ISSUE THREAD

**Issue by bwajtr** [vaadin/docs#2224]
Vaadin 24 documentation:

The following page contains this sentence:

> Since Vaadin 24.0 this mode is used when the configuration parameter `frontend.hotdeploy` is set to true, see [Configuration Properties](https://vaadin.com/docs/next/configuration/properties) for more information.

Click the link and go to the "Configuration Properties" page -> however `frontend.hotdeploy` is nowhere to be found there, no additional description given.

**Comment by jouni** [comment]
The documentation for that property was added here: https://github.com/vaadin/docs/pull/2157/files#diff-9b3aee6700678b3fa43aee33bb86372905ac8c87292663e985ca5f7d297e422dR147-R149

Due to a build failure, it was not deployed until today (you might need to clear the browser cache to see it).

**Comment by jouni** [comment]
Oh, but now I realize the change was made to the `latest` branch (v23), instead of the `next` branch (v24). We’ll merge `next` to `latest` soon (once v24 is final), but we should remove any properties that are not actually available in v23 from the v23 docs.

@caalador, I assume the `hotdeploy` property is only for v24. Are there any other properties that don't apply to v23?

**Comment by caalador** [comment]
@jouni `frontend.hotdeploy` should be the only one that is not in 23
