### ISSUE TITLE
Typescript Grid context menu behaving weirdly

### ISSUE THREAD

**Issue by mrgreywater** [vaadin/docs#2309]
### Description

https://user-images.githubusercontent.com/2902403/227583357-0f0ef1c1-f0eb-40cc-a127-6a47b027f082.mp4

### Expected outcome

Behavior between Typescript and Java matches.

### Minimal reproducible example

https://vaadin.com/docs/latest/components/context-menu -> Best Practices

### Steps to reproduce

Open https://vaadin.com/docs/latest/components/context-menu

Compare behavior of best practices example between typescript and java

### Environment

Vaadin version(s): 24.0
OS: Any

**Comment by mrgreywater** [comment]
@TatuLund If it's not a bug in Vaadin 24 then it must be a bug in Vaadin 23, because there it looks alright, with the same typescript code...

**Comment by jouni** [comment]
The code for both examples looks correct. This actually looks like a bug in the `<vaadin-menu-bar>` component, that it collapses the single "..." item because of too little horizontal space. 

That said, maybe the correct example code here would be to place the menu items on the root level, and set a fixed with on the Menu Bar component, forcing it to collapse all items into the overflow menu (instead of creating an “artificial” overflow menu item manually).
