### ISSUE TITLE
Fusion: mention how to generate a properly configured theme folder in my app in v19 upgrade guide.

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/docs#260]
V19 has a new feature custom theme, but it's not mentioned in the [v19 upgrade doc](https://vaadin.com/docs-beta/latest/guide/upgrading/#changes-in-vaadin-19).

Should at link to https://vaadin.com/docs-beta/latest/ds/customization/custom-theme/ to guide user on how to use a custom theme in their application.

**Comment by jouni** [comment]
Does this actually affect an existing application’s upgrade? Does something break in existing apps because of the improved theming support?

We shouldn’t list all the new features in the upgrading guide, only the things that explicitly require changes to the application code when upgrading the Vaadin version.

**Comment by platosha** [comment]
Indeed this feels more like a release note about a new feature.

I initially thought we could mention migrating styling of existing views using a custom theme here. But it would be too much to describe theming and styling of Fusion views in detail in upgrade guide, and we don’t have much if anything to link to yet (see #249 and #250).

**Comment by haijian-vaadin** [comment]
Close in prefer of https://github.com/vaadin/docs/issues/249 and https://github.com/vaadin/docs/issues/250
