### ISSUE TITLE
Embedded Jetty production instructions are not fit for production

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/docs#304]
The ["Deploying to Production" -> "Deploying Using Jetty"](https://vaadin.com/docs/v14/guide/production/jetty) instructions for Embedded Jetty create a configuration that unnecessarily exposes server resources to the client.

**Comment by jouni** [comment]
Thanks! Can you suggest a fix, or where to look for the correct info?

**Comment by OlliTietavainenVaadin** [comment]
https://github.com/mvysny/vaadin14-embedded-jetty was suggested by @mvysny

**Comment by jouni** [comment]
@mvysny, can you elaborate a bit more what we should update in the docs?

**Comment by mvysny** [comment]
I'd suggest to either modify the docs and update the Main class with the one from the example app: https://github.com/mvysny/vaadin14-embedded-jetty/blob/master/src/main/java/com/vaadin/starter/skeleton/Main.java

Alternatively remove the main method and simply add a link towards the example project at https://github.com/mvysny/vaadin14-embedded-jetty .

**Comment by jouni** [comment]
Okay thanks! Would it be okay to simply copy-paste the source for the class that you linked to, or would it need some modifications to fit the documentation article?

Would be great if you could make a pull request with a concrete suggestion, because I don’t feel confident in making any suggestions or updates regarding this. Not sure if @magi42 has any more confidence?

**Comment by mvysny** [comment]
Sure go ahead and copy-paste the source of the class. Only note:
* The project must not use `src/main/webapp` but instead `src/resources/webapp`. The reason is that we're not building WAR file but a JAR file; placing webapp into resources makes sure the webapp folder is correctly packaged into the jar file.
* An empty file named `ROOT` needs to be placed in the `src/resources/webapp`, in order for the launcher to correctly configure Jetty to serve files from that folder.

**Comment by jouni** [comment]
I wonder if these changes improved the situation: https://github.com/vaadin/docs/pull/319

**Comment by mvysny** [comment]
Sorry the diff is littered with Vale warnings. Can you point me out to the particular change which fixes this issue?

**Comment by jouni** [comment]
https://github.com/vaadin/docs/commit/312acbc7aa4d07eb76aa3335fefaf2c04c708453

**Comment by mvysny** [comment]
> Like it is done by default in Spring Boot applications, many servlet containers can be embedded to your application and this way packaged as executable JAR files. Follow the examples you find from your favourite Servlet container.

A good start, but I'd definitely link a (production-ready) example app at least for Jetty.

**Comment by tarekoraby** [comment]
Is this issue still relevant? We don't have a dedicated "Deploying Using Jetty" article anymore.

**Comment by OlliTietavainenVaadin** [comment]
@tarekoraby It would be useful to have such instructions available, yes.

**Comment by tarekoraby** [comment]
Isn't the topic already generally covered in https://vaadin.com/docs/latest/flow/production/production-build?

If not, we should open a new ticket to add Jetty-specific instructions.

**Comment by OlliTietavainenVaadin** [comment]
@tarekoraby that page covers the needed things on an abstract level, but I wouldn't know how to configure Jetty with that. Practical examples are much more useful. Creating a new issue would be good.

**Comment by jouni** [comment]
@OlliTietavainenVaadin please create a new issue which describes the documentation you think is still missing.
