### ISSUE TITLE
No "expand code" for auth.ts example at https://hilla.dev/docs/security/spring-login#use-a-hilla-login-view

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/docs#462]
![image](https://user-images.githubusercontent.com/5602528/118259712-23a71000-b4ba-11eb-81f6-f1a44f32be56.png)

**Comment by jcgueriaud1** [comment]
And the documentation does not contain the code for the Java classes:
https://github.com/vaadin/docs/blob/latest/src/main/java/com/vaadin/demo/fusion/security/authentication/UserInfo.java

**Comment by jouni** [comment]
The document lives here now: https://hilla.dev/docs/lit/guides/security/spring-login/#create-a-login-view

There’s nothing to expand, that’s the whole file. Perhaps it’s the tagged lines that make it seem so? That can be fixed with `include::[tags=**]`, which will exlude the `tag::[]` and `end::[]` lines that create the visual emphasis.
